# -*- coding: utf-8 -*-
"""examcenters_punjab,haryana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6UuKFiAifC7OtFbbDRfIdZBM5m80pgo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load CSV
df = pd.read_csv('Bhagyastore_Internship_Dataset.csv')

# Quick overview
print("Total rows:", len(df))
print("Columns:", df.columns.tolist())
df.info()
df.describe(include='all')

from google.colab import drive
drive.mount('/content/drive')

# Ensure dates are in datetime format
df['Installation_Date'] = pd.to_datetime(df['Installation_Date'], dayfirst=True)
df['Exam_Date'] = pd.to_datetime(df['Exam_Date'], dayfirst=True)

# Calculate camera failure rate
df['Failure_Rate_%'] = (df['Cameras_Installed'] - df['Working_Cameras']) / df['Cameras_Installed'] * 100



missing_center_status = df['Center_Status'].isnull().sum()
print(f"Number of missing values in 'Center_Status': {missing_center_status}")



# Describe the distribution of 'Failure_Rate_%'
print(df['Failure_Rate_%'].describe())

# Visualize the distribution of 'Failure_Rate_%'
plt.figure(figsize=(10, 6))
sns.histplot(df['Failure_Rate_%'], bins=10, kde=True)
plt.title('Distribution of Camera Failure Rate (%)')
plt.xlabel('Failure Rate (%)')
plt.ylabel('Number of Centers')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Overall metrics
print("Average Failure Rate: {:.2f}%".format(df['Failure_Rate_%'].mean()))
print("Average Maintenance Cost: ₹{:.2f}".format(df['Maintenance_Cost_INR'].mean()))
print("Number of Centers per City:\n", df['City'].value_counts())

correlation_resolution_failure = df['Resolution_Time_Hours'].corr(df['Failure_Rate_%'])
print(f"Correlation between Resolution Time (Hours) and Failure Rate (%): {correlation_resolution_failure:.2f}")

plt.figure(figsize=(10, 6))
sns.regplot(x='Failure_Rate_%', y='Resolution_Time_Hours', data=df, scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
plt.title('Relationship between Camera Failure Rate and Resolution Time')
plt.xlabel('Failure Rate (%)')
plt.ylabel('Resolution Time (Hours)')
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.show()

avg_resolution_time_by_city = df.groupby('City')['Resolution_Time_Hours'].mean().reset_index()
print("Average Resolution Time (Hours) by City:\n", avg_resolution_time_by_city)

# Group by City and describe 'Maintenance_Cost_INR'
city_maintenance_cost = df.groupby('City')['Maintenance_Cost_INR'].describe()
print("Maintenance Cost (INR) Distribution by City:\n", city_maintenance_cost)

# Visualize the distribution of 'Maintenance_Cost_INR' by 'City'
plt.figure(figsize=(14, 7))
sns.boxplot(x='City', y='Maintenance_Cost_INR', data=df, hue='City', legend=False, palette='viridis')
plt.title('Distribution of Maintenance Cost (INR) by City')
plt.xlabel('City')
plt.ylabel('Maintenance Cost (INR)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Describe the distribution of 'Issues_Reported'
print(df['Issues_Reported'].describe())

# Visualize the distribution of 'Issues_Reported'
plt.figure(figsize=(10, 6))
sns.histplot(df['Issues_Reported'], bins=3, kde=True)
plt.title('Distribution of Issues Reported')
plt.xlabel('Issues Reported')
plt.ylabel('Number of Centers')
plt.xticks(df['Issues_Reported'].unique())
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

correlation = df['Failure_Rate_%'].corr(df['Issues_Reported'])
print(f"Correlation between Failure Rate (%) and Issues Reported: {correlation:.2f}")

plt.figure(figsize=(10, 6))
sns.regplot(x='Failure_Rate_%', y='Issues_Reported', data=df, scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
plt.title('Relationship between Camera Failure Rate and Issues Reported')
plt.xlabel('Failure Rate (%)')
plt.ylabel('Issues Reported')
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.show()

# Describe the distribution of 'Maintenance_Cost_INR'
print(df['Maintenance_Cost_INR'].describe())

# Visualize the distribution of 'Maintenance_Cost_INR'
plt.figure(figsize=(10, 6))
sns.histplot(df['Maintenance_Cost_INR'], bins=10, kde=True)
plt.title('Distribution of Maintenance Cost (INR)')
plt.xlabel('Maintenance Cost (INR)')
plt.ylabel('Number of Centers')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

city_summary = df.groupby('City').agg({
    'Failure_Rate_%':'mean',
    'Maintenance_Cost_INR':'mean',
    'Center_ID':'count'
}).rename(columns={'Center_ID':'Total_Centers'})
city_summary = city_summary.sort_values('Failure_Rate_%', ascending=False)
city_summary



plt.figure(figsize=(15, 8))

# Bar plot for Average Failure Rate
plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
sns.barplot(x=city_summary.index, y='Failure_Rate_%', data=city_summary, hue='City', legend=False, palette='Reds_d')
plt.title('Average Camera Failure Rate by City')
plt.xlabel('City')
plt.ylabel('Average Failure Rate (%)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Bar plot for Average Maintenance Cost
plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
sns.barplot(x=city_summary.index, y='Maintenance_Cost_INR', data=city_summary, hue='City', legend=False, palette='Blues_d')
plt.title('Average Maintenance Cost by City')
plt.xlabel('City')
plt.ylabel('Average Maintenance Cost (INR)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

tech_summary = df.groupby('Technician').agg({
    'Failure_Rate_%':'mean',
    'Maintenance_Cost_INR':'mean',
    'Center_ID':'count'
}).rename(columns={'Center_ID':'Centers_Handled'})
tech_summary = tech_summary.sort_values('Failure_Rate_%')
tech_summary



plt.figure(figsize=(15, 8))

# Bar plot for Average Failure Rate by Technician
plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
sns.barplot(x=tech_summary.index, y='Failure_Rate_%', data=tech_summary, hue='Technician', legend=False, palette='viridis')
plt.title('Average Camera Failure Rate by Technician')
plt.xlabel('Technician')
plt.ylabel('Average Failure Rate (%)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Bar plot for Average Maintenance Cost by Technician
plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
sns.barplot(x=tech_summary.index, y='Maintenance_Cost_INR', data=tech_summary, hue='Technician', legend=False, palette='magma')
plt.title('Average Maintenance Cost by Technician')
plt.xlabel('Technician')
plt.ylabel('Average Maintenance Cost (INR)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

# Failure Rate by City
plt.figure(figsize=(12,6))
sns.barplot(x=city_summary.index, y=city_summary['Failure_Rate_%'], palette='coolwarm')
plt.title("Average Camera Failure Rate by City")
plt.ylabel("Failure Rate (%)")
plt.xticks(rotation=45)
plt.show()

# Maintenance Cost by Exam Type
plt.figure(figsize=(10,6))
sns.boxplot(x='Exam_Type', y='Maintenance_Cost_INR', data=df, palette='Set2')
plt.title("Maintenance Cost Distribution by Exam Type")
plt.show()

# Technician Performance
plt.figure(figsize=(12,6))
sns.barplot(x=tech_summary.index, y=tech_summary['Failure_Rate_%'], palette='viridis')
plt.title("Technician Performance (Lower Failure Rate is Better)")
plt.ylabel("Average Failure Rate (%)")
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x=tech_summary.index, y='Centers_Handled', data=tech_summary, hue='Technician', legend=False, palette='coolwarm')
plt.title('Number of Centers Handled by Technician')
plt.xlabel('Technician')
plt.ylabel('Number of Centers Handled')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Failure_Rate_%', y='Maintenance_Cost_INR', hue='Technician', data=tech_summary, s=100)

for i, row in tech_summary.iterrows():
    plt.text(row['Failure_Rate_%'] + 0.1, row['Maintenance_Cost_INR'], i, fontsize=9)

plt.title('Relationship between Average Failure Rate and Average Maintenance Cost by Technician')
plt.xlabel('Average Failure Rate (%)')
plt.ylabel('Average Maintenance Cost (INR)')
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(12, 6))
sns.barplot(x='City', y='Resolution_Time_Hours', data=avg_resolution_time_by_city, palette='coolwarm', hue='City', legend=False)
plt.title('Average Resolution Time (Hours) by City')
plt.xlabel('City')
plt.ylabel('Average Resolution Time (Hours)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print(tech_summary.describe())

correlation_matrix = tech_summary[['Failure_Rate_%', 'Maintenance_Cost_INR', 'Centers_Handled']].corr()
print("Correlation Matrix for Technician Summary:\n", correlation_matrix)

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix for Technician Summary')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Centers_Handled', y='Maintenance_Cost_INR', hue='Technician', data=tech_summary, s=100)

for i, row in tech_summary.iterrows():
    plt.text(row['Centers_Handled'] + 0.5, row['Maintenance_Cost_INR'], i, fontsize=9)

plt.title('Relationship between Centers Handled and Average Maintenance Cost by Technician')
plt.xlabel('Number of Centers Handled')
plt.ylabel('Average Maintenance Cost (INR)')
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Centers_Handled', y='Failure_Rate_%', hue='Technician', data=tech_summary, s=100)

for i, row in tech_summary.iterrows():
    plt.text(row['Centers_Handled'] + 0.5, row['Failure_Rate_%'], i, fontsize=9)

plt.title('Relationship between Centers Handled and Average Failure Rate by Technician')
plt.xlabel('Number of Centers Handled')
plt.ylabel('Average Failure Rate (%)')
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.show()



df.info()

print(df.describe(include='all'))

print(tech_summary)

tech_city_performance = df.groupby(['Technician', 'City']).agg({
    'Failure_Rate_%': 'mean',
    'Maintenance_Cost_INR': 'mean',
    'Center_ID': 'count' # Count centers handled by this technician in this city
}).rename(columns={'Center_ID': 'Centers_in_City'})

print("Technician Performance by City:\n")
print(tech_city_performance)

"""# Step 8: Save Cleaned Dataset
df.to_csv('bhagyastore_dataset_cleaned.csv', index=False)
print("\nCleaned dataset saved as 'bhagyastore_dataset_cleaned.csv'")
"""

from google.colab import files
files.download('bhagyastore_dataset_cleaned.csv')

# Commented out IPython magic to ensure Python compatibility.
# %who